### ISSUE TITLE
VC 2019 compile error

### ISSUE THREAD

**Issue by mediabuff** [microsoft/IPC.Bond#8]
`1>------ Build started: Project: TestManagedTransport, Configuration: Debug x64 ------
1>Managed.cpp
1>Unknown compiler version - please run the configure tests and report the results
1>C:\MyDevProjects\MyProjectsThirdPartyLibs\IPC.Bond\IPC\Inc\IPC\Managed\detail\NativeObject.h(92,1): error C2027: use of undefined type 'IPC::Containers::Vector<IPC::Containers::Vector<int>>'
1>C:\MyDevProjects\MyProjectsThirdPartyLibs\IPC.Bond\IPC\Inc\IPC\Containers\Managed\detail\Vector.h(24): message : see declaration of 'IPC::Containers::Vector<IPC::Containers::Vector<int>>'
1>C:\MyDevProjects\MyProjectsThirdPartyLibs\IPC.Bond\IPC\Inc\IPC\Managed\detail\NativeObject.h(89): message : while compiling class template member function 'T &IPC::Managed::detail::NativeObject<T>::Object::get(void)'
1>        with
1>        [
1>            T=IPC::Containers::Vector<IPC::Containers::Vector<int>>
1>        ]
1>C:\MyDevProjects\MyProjectsThirdPartyLibs\IPC.Bond\IPC\Inc\IPC\Containers\Managed\detail\Vector.h(163): message : see reference to class template instantiation 'IPC::Managed::detail::NativeObject<IPC::Containers::Vector<IPC::Containers::Vector<int>>>' being compiled
1>C:\MyDevProjects\MyProjectsThirdPartyLibs\IPC.Bond\IPC\TestManagedTransport\Src\Managed.cpp(15): message : see reference to class template instantiation 'IPC::Containers::Managed::detail::Vector<IPC::Containers::Managed::IVector<T> ^>' being compiled
1>        with
1>        [
1>            T=int
1>        ]
1>Done building project "TestManagedTransport.vcxproj" -- FAILED.
2>------ Build started: Project: UnitTestsManaged, Configuration: Debug x64 ------
2>CSC : error CS0006: Metadata file 'C:\MyDevProjects\MyProjectsThirdPartyLibs\IPC.Bond\IPC\x64\Debug\TestManagedTransport.dll' could not be found
========== Build: 0 succeeded, 2 failed, 8 up-to-date, 0 skipped ==========`

**Comment by mediabuff** [comment]
Additionally,

`1>------ Build started: Project: UnitTests, Configuration: Debug x64 ------
1>libboost_thread-vc140-mt-gd-1_63.lib(thread.obj) : error LNK2005: "void * __cdecl boost::detail::get_tss_data(void const *)" (?get_tss_data@detail@boost@@YAPEAXPEBX@Z) already defined in boost_thread-vc140-mt-gd.lib(boost_thread-vc142-mt-gd-x64-1_71.dll)
1>C:\MyDevProjects\MyProjectsThirdPartyLibs\IPC.Bond\x64\Debug\IPC.Bond.UnitTests.exe : fatal error LNK1169: one or more multiply defined symbols found
1>Done building project "UnitTests.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 5 up-to-date, 0 skipped ==========`

**Comment by ara-ayvazyan** [comment]
I've upgrade to `vc142` and `Boost` 1.71 (#12).
